apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: jarich/backend-app:v1.9.6
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-app
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: LoadBalancer
