apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: jarich/frontend-app:v1.3
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-app
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
