apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-app
  namespace: monitoring #namespace the Prometheus instance is running in
  labels:
    app: backend-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-app
  endpoints:
  - port: http
#    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default